name: wcdonalds_app
description: Order Fast Food Now.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  sqflite: ^2.0.0
  path: ^1.8.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  shared_preferences: ^2.2.0
  sqflite_common_ffi: ^2.2.5 # Useful for testing if environment supported, or just good practice
  sqflite_common_ffi_web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
